// Generated by Qodo Gen
import React from 'react';
import Home from './page';
import { render } from '@testing-library/react';
import '@testing-library/jest-dom';

describe('Home', () => {
  // Menu renders correctly with all navigation items and their icons
  it('should render menu with all navigation items and their icons', () => {
    const { getByText, container } = render(<Home />);

    expect(getByText('Navigation One')).toBeInTheDocument();
    expect(container.querySelector('.anticon-mail')).toBeInTheDocument();

    expect(getByText('Navigation Two')).toBeInTheDocument();
    expect(container.querySelector('.anticon-appstore')).toBeInTheDocument();
    expect(getByText('Navigation Two').closest('li')).toHaveAttribute('aria-disabled', 'true');

    expect(getByText('Navigation Three - Submenu')).toBeInTheDocument();
    expect(container.querySelector('.anticon-setting')).toBeInTheDocument();

    expect(getByText('Navigation Four - Link')).toBeInTheDocument();
    expect(getByText('Navigation Four - Link').closest('a')).toHaveAttribute(
      'href',
      'https://ant.design',
    );
  });

  // Handle failed API responses from both endpoints
  // it("should handle failed API responses when opening drawer", async () => {
  //   global.fetch = jest
  //     .fn()
  //     .mockImplementationOnce(() =>
  //       Promise.reject(new Error("Local API failed"))
  //     )
  //     .mockImplementationOnce(() =>
  //       Promise.reject(new Error("External API failed"))
  //     );

  //   const { getByText } = render(<Home />);
  //   const openButton = getByText("Open Drawer");

  //   await act(async () => {
  //     fireEvent.click(openButton);
  //   });

  //   expect(getByText("TEST MY PAGE -")).toBeInTheDocument();
  //   expect(getByText("Loading Drawer")).toBeInTheDocument();
  //   expect(fetch).toHaveBeenCalledTimes(2);
  // });
});
